repo: # name of the repository on Github
  host: 123.456.789.0 # domain name or local IP address of your app server
  key: /home/ubuntu/.ssh/boss # path to your private SSH key
  path: /srv # path to your app
